"""Generate db/seeds/001_zones.sql from real OpenStreetMap protected-area boundaries.

Run:  python scripts/build_zone_seed.py
Data: (c) OpenStreetMap contributors, ODbL 1.0 (https://www.openstreetmap.org/copyright).
Nominatim usage policy: identify ourselves, at most 1 request/second. One lookup call is enough.
"""

import json
import math
from pathlib import Path

import httpx

USER_AGENT = "biodiv-student-project/0.1 (+https://github.com/tfthushaar/biodiversity)"
OUT = Path(__file__).resolve().parent.parent / "db" / "seeds" / "001_zones.sql"

# slug, display name, group, ISO country, OSM id (W=way, R=relation)
ZONES = [
    ("bandipur", "Bandipur National Park", "Bandipur-Nagarahole", "IN", "W159049291"),
    ("nagarahole", "Nagarahole National Park", "Bandipur-Nagarahole", "IN", "R12154449"),
    # Wayanad Wildlife Sanctuary has no usable OSM polygon (W545992145 is degenerate, 0 km2).
    # Mudumalai is the contiguous Nilgiri landscape where Bandipur, Wayanad and Tamil Nadu meet.
    ("mudumalai", "Mudumalai National Park", "Nilgiri", "IN", "W159049306"),
    ("serengeti", "Serengeti National Park", "Serengeti", "TZ", "R4475047"),
]


MIN_AREA_KM2 = 10.0  # a real reserve is never smaller; catches degenerate OSM objects


def approx_area_km2(geo: dict) -> float:
    """Rough planar area (equirectangular shoelace). Only a sanity check, not for analysis."""
    polys = geo["coordinates"] if geo["type"] == "MultiPolygon" else [geo["coordinates"]]
    total = 0.0
    for poly in polys:
        for i, ring in enumerate(poly):
            kx = 111.32 * math.cos(math.radians(sum(p[1] for p in ring) / len(ring)))
            pairs = zip(ring, ring[1:] + ring[:1], strict=True)
            twice = sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in pairs)
            total += abs(twice) / 2 * kx * 110.57 * (1 if i == 0 else -1)  # holes subtract
    return total


def fetch() -> dict[str, dict]:
    ids = ",".join(z[4] for z in ZONES)
    res = httpx.get(
        "https://nominatim.openstreetmap.org/lookup",
        params={
            "osm_ids": ids,
            "format": "jsonv2",
            "polygon_geojson": 1,
            "polygon_threshold": 0.0005,  # ~50 m simplification
        },
        headers={"User-Agent": USER_AGENT},
        timeout=60,
    )
    res.raise_for_status()
    return {f"{r['osm_type'][0].upper()}{r['osm_id']}": r for r in res.json()}


def main() -> None:
    found = fetch()
    rows = []
    for slug, name, group, country, osm in ZONES:
        rec = found.get(osm)
        if rec is None:
            raise SystemExit(f"OSM object {osm} ({name}) not returned by Nominatim")
        geo = rec["geojson"]
        if geo["type"] not in ("Polygon", "MultiPolygon"):
            raise SystemExit(f"{name}: unexpected geometry {geo['type']}")
        area = approx_area_km2(geo)
        if area < MIN_AREA_KM2:
            raise SystemExit(f"{name} ({osm}): area {area:.1f} km2 is implausible, refusing")
        print(f"  {slug:<11} ~{area:>7.0f} km2  {osm}")
        note = f"OpenStreetMap contributors (ODbL), {osm}"
        rows.append(
            f"({slug!r}, {name!r}, {group!r}, {country!r}, {note!r},\n"
            f" ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON($geo${json.dumps(geo)}$geo$), 4326)))"
        )
    sql = (
        "-- GENERATED by scripts/build_zone_seed.py. Do not edit by hand.\n"
        "-- Boundaries (c) OpenStreetMap contributors, ODbL 1.0.\n"
        "insert into zones (slug, name, group_name, country, source_note, geom) values\n"
        + ",\n".join(rows)
        + "\non conflict (slug) do update set\n"
        "  name = excluded.name, group_name = excluded.group_name, country = excluded.country,\n"
        "  source_note = excluded.source_note, geom = excluded.geom;\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT} ({len(sql) // 1024} KiB, {len(rows)} zones)")


if __name__ == "__main__":
    main()
