# ruff: noqa: E501
"""Build paper.md from docs/paper_template.md and the numbers in the database summary.

    python scripts/dataset_summary.py           # refresh docs/metrics/dataset_summary.json
    python scripts/build_paper.py               # fill the template and write paper.md

The template holds the prose. Every table is generated by scripts/paper_tables.py and every number
that comes from the data is a {{TOKEN}} filled here, so the paper cannot disagree with the data.
The build fails if a token has no value.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import paper_tables as T  # noqa: E402

S = T.S
KB = json.loads(Path("db/seeds/knowledge.json").read_text(encoding="utf-8"))


def by_source(name: str) -> int:
    return sum(r["records"] for r in S["records_by_park_and_source"] if r["source"] == name)


def trend(slug: str, series: str) -> dict:
    return S["analysis_detail"][slug]["trend"][series]


def p_value(p: float) -> str:
    return "<0.001" if p < 0.001 else f"{p:.2f}"


def cert_phrase() -> str:
    names = {"review": "{n} summarising reviews or species profiles", "observational": "{n} field observations",
             "preliminary": "{n} preliminary", "unverified_concern": "{n} unverified concerns",
             "experimental": "{n} controlled experiment"}
    got = S["knowledge_base"]["findings_by_certainty"]
    parts = [names[k].format(n=got[k]) for k in names if got.get(k)]
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def values() -> dict[str, str]:
    snap = datetime.fromisoformat(S["computed_at"])
    ever = S["hotspots"]["everglades"]["0.02"]
    co = S["analysis_detail"]["smokies"]["cooccurrence"]
    fetched = S["records_fetched_by_source"]
    refused_n = sum(S["records_refused_by_reason"]["USGS NAS"].values())
    kb = S["knowledge_base"]
    certainty = kb["findings_by_certainty"]
    quotes = sum(len(r["quotes"]) for r in KB["playbooks"] + KB["impact_findings"])
    ever_inv, ever_obs = T.trend_pair("everglades")
    mud_inv, mud_obs = T.trend_pair("mudumalai")
    inv_total = sum(S["invasive_records_by_park"].values())
    share = {z: S["invasive_records_by_park"].get(z, 0) / sum(
        r["records"] for r in S["records_by_park_and_source"] if r["park"] == z) for z in T.ORDER}
    others = {z: v for z, v in share.items() if z != "everglades"}
    lo, hi = min(others, key=others.get), max(others, key=others.get)
    india = [z for z in T.ORDER if T.COUNTRY[z] == "IN"]

    def sp_records(name: str) -> int:
        return sum(x["records"] for z in india for x in S["invasive_species_by_park"].get(z, [])
                   if x["species"] == name)

    cov = S["evidence_coverage"]
    in_find = [cov[z]["with_cited_findings"] for z in india]
    in_spp = [cov[z]["invasive_species"] for z in india]
    alerts = S["alerts"]
    alert_text = "; ".join(
        f"{a['species']} in {T.NAMES[a['park']]} (first record {a['first_record'][:7]})" for a in alerts)
    return {
        "INV_TOTAL": T.n(inv_total),
        "EVER_SHARE": f"{100 * share['everglades']:.0f}",
        "SHARE_LOW": f"{100 * share[lo]:.1f}",
        "SHARE_LOW_PARK": T.NAMES[lo],
        "SHARE_HIGH": f"{100 * share[hi]:.1f}",
        "SHARE_HIGH_PARK": T.NAMES[hi],
        "LANTANA_RECORDS": str(sp_records("Lantana camara")),
        "SENNA_RECORDS": str(sp_records("Senna spectabilis")),
        "EVER_COVER_PCT": f"{100 * cov['everglades']['records_of_species_with_findings'] / cov['everglades']['records']:.0f}",
        "IN_FIND_MIN": str(min(in_find)),
        "IN_FIND_MAX": str(max(in_find)),
        "IN_SPP_MIN": str(min(in_spp)),
        "IN_SPP_MAX": str(max(in_spp)),
        "ALERT_COUNT": str(len(alerts)),
        "ALERT_TEXT": alert_text,
        "EVER_Y0": str(S["analysis_detail"]["everglades"]["trend"]["years"][0]),
        "EVER_Y1": str(S["analysis_detail"]["everglades"]["trend"]["years"][1]),
        "MUD_Y0": str(S["analysis_detail"]["mudumalai"]["trend"]["years"][0]),
        "MUD_Y1": str(S["analysis_detail"]["mudumalai"]["trend"]["years"][1]),
        "SNAPSHOT": f"{snap.day} {snap:%B %Y}",
        "TOTAL_RECORDS": T.n(S["total_records"]),
        "ITOTAL": T.n(by_source("iNaturalist")),
        "GTOTAL": T.n(by_source("GBIF occurrences")),
        "NTOTAL": T.n(by_source("USGS NAS")),
        "DBMB": f"{S['database_bytes'] / 1e6:.0f}",
        "FETCHED_I": T.n(fetched["iNaturalist"]),
        "FETCHED_G": T.n(fetched["GBIF occurrences"]),
        "FETCHED_N": T.n(fetched["USGS NAS"]),
        "REFUSED_N": T.n(refused_n),
        "I_KEPT_PCT": f"{100 * by_source('iNaturalist') / fetched['iNaturalist']:.0f}",
        "G_KEPT_PCT": f"{100 * by_source('GBIF occurrences') / fetched['GBIF occurrences']:.0f}",
        "HOT_EVER_SHARE": f"{100 * ever['share_in_top_10_percent_of_cells']:.0f}",
        "HOT_EVER_MAX": T.n(ever["busiest_cell_records"]),
        "HOT_EVER_N": T.n(ever["records"]),
        "HOT_EVER_CELLS": T.n(ever["occupied_cells"]),
        "SMOKIES_CELLS": T.n(co["cells_usable"]),
        "SMOKIES_RHO": f"{co['spearman_rho']:.2f}",
        "SMOKIES_LO": f"{co['ci95'][0]:.2f}",
        "SMOKIES_HI": f"{co['ci95'][1]:.2f}",
        "EVER_YEARS": str(trend("everglades", "invasive_per_observation")["n"]),
        "EVER_TAU": f"{ever_inv['tau']:.2f}",
        "EVER_P": p_value(ever_inv["p_value"]),
        "EVER_SLOPE": f"{ever_inv['slope']:.4f}",
        "EVER_NP": p_value(ever_obs["p_value"]),
        "MUD_YEARS": str(trend("mudumalai", "invasive_per_observation")["n"]),
        "MUD_TAU": f"{mud_inv['tau']:.2f}",
        "MUD_P": p_value(mud_inv["p_value"]),
        "MUD_NP": p_value(mud_obs["p_value"]),
        "KB_FINDINGS": str(kb["findings"]),
        "KB_PLAYBOOKS": str(kb["management_options"]),
        "KB_QUOTES": str(quotes),
        "KB_SOURCES": str(len(KB["sources"])),
        "KB_CERT": cert_phrase(),
        "KB_REVIEW": str(certainty.get("review", 0)),
        "KB_EXP": str(certainty.get("experimental", 0)),
    }


def build(template: str, out: str) -> int:
    text = Path(template).read_text(encoding="utf-8")
    vals = values()
    text = re.sub(r"\{\{(\w+)\}\}", lambda m: vals[m.group(1)], text)  # KeyError names a missing value
    text = re.sub(
        r"<!-- table:(\w+) -->.*?<!-- /table -->",
        lambda m: "<!-- table:" + m.group(1) + " -->\n" + T.TABLES[m.group(1)]() + "\n<!-- /table -->",
        text, flags=re.S,
    )
    Path(out).write_text(text, encoding="utf-8")
    return len(vals)


if __name__ == "__main__":
    template = sys.argv[1] if len(sys.argv) > 1 else "docs/paper_template.md"
    out = sys.argv[2] if len(sys.argv) > 2 else "paper.md"
    print(f"wrote {out} from {template} ({build(template, out)} values)")
