# ruff: noqa: E501
"""Build paper.md from docs/paper_template.md and the numbers in the database summary.

    python scripts/dataset_summary.py           # refresh docs/metrics/dataset_summary.json
    python scripts/build_paper.py               # fill the template and write paper.md

The template holds the prose. Every table is generated by scripts/paper_tables.py and every number
that comes from the data is a {{TOKEN}} filled here, so the paper cannot disagree with the data.
The build fails if a token has no value.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import paper_tables as T  # noqa: E402

S = T.S
KB = json.loads(Path("db/seeds/knowledge.json").read_text(encoding="utf-8"))


def by_source(name: str) -> int:
    return sum(r["records"] for r in S["records_by_park_and_source"] if r["source"] == name)


def trend(slug: str, series: str) -> dict:
    return S["analysis_detail"][slug]["trend"][series]


def p_value(p: float) -> str:
    if p < 0.001:
        return "<0.001"
    return f"{p:.3f}" if p < 0.1 else f"{p:.2f}"


def cert_phrase() -> str:
    names = {"review": "{n} summarising reviews or species profiles", "observational": "{n} field observations",
             "preliminary": "{n} preliminary", "unverified_concern": "{n} unverified concerns",
             "experimental": "{n} controlled experiment"}
    got = S["knowledge_base"]["findings_by_certainty"]
    parts = [names[k].format(n=got[k]) for k in names if got.get(k)]
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def count_tests() -> int:
    """Tests run in parks that meet the minimums: one correlation, and one trend test per series."""
    n = 0
    for a in S["analysis_detail"].values():
        n += 1 if "spearman_rho" in a["cooccurrence"] else 0
        n += sum(k in a["trend"] for k in ("invasive_per_observation", "native_per_observation"))
    return n


N_TESTS = count_tests()


def check_claims() -> None:
    """The template states directions and significance. Fail the build if the data no longer
    supports a statement, so the prose is revised and not left to contradict the numbers."""
    ad, bonf = S["analysis_detail"], 0.05 / N_TESTS
    sm, ev = ad["smokies"], ad["everglades"]
    ev_inv, ev_nat = T.trend_pair("everglades")
    sm_inv, sm_nat = T.trend_pair("smokies")
    mu_inv, mu_nat = T.trend_pair("mudumalai")
    claims = {
        "Smokies correlation is positive with an interval above zero": sm["cooccurrence"]["ci95"][0] > 0,
        "Everglades correlation is positive with an interval including zero":
            ev["cooccurrence"]["spearman_rho"] > 0 and ev["cooccurrence"]["ci95"][0] <= 0,
        "Everglades invasive trend rose, p below 0.05 and above the Bonferroni threshold":
            ev_inv["tau"] > 0 and bonf < ev_inv["p_value"] < 0.05,
        "Everglades native trend is not significant": ev_nat["p_value"] >= 0.05,
        "Smokies invasive trend is not significant": sm_inv["p_value"] >= 0.05,
        "Smokies native trend fell, p below 0.05 and above the Bonferroni threshold":
            sm_nat["tau"] < 0 and bonf < sm_nat["p_value"] < 0.05,
        "Mudumalai trends are not significant": mu_inv["p_value"] >= 0.05 and mu_nat["p_value"] >= 0.05,
        "Exactly Mudumalai, Everglades and the Smokies meet the trend minimum and only the Everglades "
        "and Smokies the correlation minimum":
            {z for z, a in ad.items() if "invasive_per_observation" in a["trend"]}
            == {"mudumalai", "everglades", "smokies"}
            and {z for z, a in ad.items() if "spearman_rho" in a["cooccurrence"]} == {"everglades", "smokies"},
    }
    failed = [k for k, ok in claims.items() if not ok]
    if failed:
        message = "paper template no longer matches the data; revise Sections 3.4 and 4:"
        raise SystemExit(message + "\n  - " + ("\n  - ").join(failed))


def values() -> dict[str, str]:
    snap = datetime.fromisoformat(S["computed_at"])
    ever = S["hotspots"]["everglades"]["0.02"]
    co = S["analysis_detail"]["smokies"]["cooccurrence"]
    fetched = S["records_fetched_by_source"]
    refused_n = sum(S["records_refused_by_reason"]["USGS NAS"].values())
    kb = S["knowledge_base"]
    certainty = kb["findings_by_certainty"]
    quotes = sum(len(r["quotes"]) for r in KB["playbooks"] + KB["impact_findings"])
    ever_inv, ever_obs = T.trend_pair("everglades")
    mud_inv, mud_obs = T.trend_pair("mudumalai")
    inv_total = sum(S["invasive_records_by_park"].values())
    share = {z: S["invasive_records_by_park"].get(z, 0) / sum(
        r["records"] for r in S["records_by_park_and_source"] if r["park"] == z) for z in T.ORDER}
    others = {z: v for z, v in share.items() if z != "everglades"}
    lo, hi = min(others, key=others.get), max(others, key=others.get)
    india = [z for z in T.ORDER if T.COUNTRY[z] == "IN"]

    def sp_records(name: str) -> int:
        return sum(x["records"] for z in india for x in S["invasive_species_by_park"].get(z, [])
                   if x["species"] == name)

    cov = S["evidence_coverage"]
    in_find = [cov[z]["with_cited_findings"] for z in india]
    in_spp = [cov[z]["invasive_species"] for z in india]
    alerts = S["alerts"]
    alert_text = "; ".join(
        f"{a['species']} in {T.NAMES[a['park']]} (first record {a['first_record'][:7]})" for a in alerts)
    ad = S["analysis_detail"]
    ev_co = ad["everglades"]["cooccurrence"]
    sm_inv, sm_nat = T.trend_pair("smokies")
    mud_nat = trend("mudumalai", "native_per_observation")
    mix = S["invasive_records_by_period_and_source"]["everglades"]
    pre = mix.get("to 2009", {})
    late = mix.get("2020 on", {})
    smk_hot = S["hotspots"]["smokies"]["0.02"]
    n_tests = N_TESTS
    return {
        "N_TESTS": str(n_tests),
        "BONF": f"{0.05 / n_tests:.4f}",
        "EVER_CELLS": T.n(ev_co["cells_usable"]),
        "EVER_RHO": f"{ev_co['spearman_rho']:.2f}",
        "EVER_RHO_LO": f"{ev_co['ci95'][0]:.2f}",
        "EVER_RHO_HI": f"{ev_co['ci95'][1]:.2f}",
        "EVER_NTAU": f"{ever_obs['tau']:.2f}",
        "SMK_TAU": f"{sm_inv['tau']:.2f}",
        "SMK_P": p_value(sm_inv["p_value"]),
        "SMK_NTAU": f"{sm_nat['tau']:.2f}",
        "SMK_NP": p_value(sm_nat["p_value"]),
        "SMK_YEARS": str(sm_inv["n"]),
        "SMK_Y0": str(ad["smokies"]["trend"]["years"][0]),
        "SMK_Y1": str(ad["smokies"]["trend"]["years"][1]),
        "MUD_NTAU": f"{mud_nat['tau']:.2f}",
        "SMK_INV": T.n(smk_hot["records"]),
        "SMK_CELLS_OCC": T.n(smk_hot["occupied_cells"]),
        "SMK_ONE": T.n(smk_hot["cells_with_one_record"]),
        "EVER_PRE_TOTAL": T.n(sum(pre.values())),
        "EVER_PRE_USGS": T.n(pre.get("USGS NAS", 0)),
        "EVER_LATE_TOTAL": T.n(sum(late.values())),
        "EVER_LATE_GBIF": T.n(late.get("GBIF occurrences", 0)),
        "INV_TOTAL": T.n(inv_total),
        "EVER_SHARE": f"{100 * share['everglades']:.0f}",
        "SHARE_LOW": f"{100 * share[lo]:.1f}",
        "SHARE_LOW_PARK": T.NAMES[lo],
        "SHARE_HIGH": f"{100 * share[hi]:.1f}",
        "SHARE_HIGH_PARK": T.NAMES[hi],
        "LANTANA_RECORDS": str(sp_records("Lantana camara")),
        "SENNA_RECORDS": str(sp_records("Senna spectabilis")),
        "EVER_COVER_PCT": f"{100 * cov['everglades']['records_of_species_with_findings'] / cov['everglades']['records']:.0f}",
        "IN_FIND_MIN": str(min(in_find)),
        "IN_FIND_MAX": str(max(in_find)),
        "IN_SPP_MIN": str(min(in_spp)),
        "IN_SPP_MAX": str(max(in_spp)),
        "ALERT_COUNT": str(len(alerts)),
        "ALERT_TEXT": alert_text,
        "EVER_Y0": str(S["analysis_detail"]["everglades"]["trend"]["years"][0]),
        "EVER_Y1": str(S["analysis_detail"]["everglades"]["trend"]["years"][1]),
        "MUD_Y0": str(S["analysis_detail"]["mudumalai"]["trend"]["years"][0]),
        "MUD_Y1": str(S["analysis_detail"]["mudumalai"]["trend"]["years"][1]),
        "SNAPSHOT": f"{snap.day} {snap:%B %Y}",
        "TOTAL_RECORDS": T.n(S["total_records"]),
        "ITOTAL": T.n(by_source("iNaturalist")),
        "GTOTAL": T.n(by_source("GBIF occurrences")),
        "NTOTAL": T.n(by_source("USGS NAS")),
        "DBMB": f"{S['database_bytes'] / 1e6:.0f}",
        "FETCHED_I": T.n(fetched["iNaturalist"]),
        "FETCHED_G": T.n(fetched["GBIF occurrences"]),
        "FETCHED_N": T.n(fetched["USGS NAS"]),
        "REFUSED_N": T.n(refused_n),
        "I_KEPT_PCT": f"{100 * by_source('iNaturalist') / fetched['iNaturalist']:.0f}",
        "G_KEPT_PCT": f"{100 * by_source('GBIF occurrences') / fetched['GBIF occurrences']:.0f}",
        "HOT_EVER_SHARE": f"{100 * ever['share_in_top_10_percent_of_cells']:.0f}",
        "HOT_EVER_MAX": T.n(ever["busiest_cell_records"]),
        "HOT_EVER_N": T.n(ever["records"]),
        "HOT_EVER_CELLS": T.n(ever["occupied_cells"]),
        "SMOKIES_CELLS": T.n(co["cells_usable"]),
        "SMOKIES_RHO": f"{co['spearman_rho']:.2f}",
        "SMOKIES_LO": f"{co['ci95'][0]:.2f}",
        "SMOKIES_HI": f"{co['ci95'][1]:.2f}",
        "EVER_YEARS": str(trend("everglades", "invasive_per_observation")["n"]),
        "EVER_TAU": f"{ever_inv['tau']:.2f}",
        "EVER_P": p_value(ever_inv["p_value"]),
        "EVER_SLOPE": f"{ever_inv['slope']:.4f}",
        "EVER_NP": p_value(ever_obs["p_value"]),
        "MUD_YEARS": str(trend("mudumalai", "invasive_per_observation")["n"]),
        "MUD_TAU": f"{mud_inv['tau']:.2f}",
        "MUD_P": p_value(mud_inv["p_value"]),
        "MUD_NP": p_value(mud_obs["p_value"]),
        "KB_FINDINGS": str(kb["findings"]),
        "KB_PLAYBOOKS": str(kb["management_options"]),
        "KB_QUOTES": str(quotes),
        "KB_SOURCES": str(len(KB["sources"])),
        "KB_CERT": cert_phrase(),
        "KB_REVIEW": str(certainty.get("review", 0)),
        "KB_EXP": str(certainty.get("experimental", 0)),
    }


def build(template: str, out: str) -> int:
    text = Path(template).read_text(encoding="utf-8")
    check_claims()
    vals = values()
    text = re.sub(r"\{\{(\w+)\}\}", lambda m: vals[m.group(1)], text)  # KeyError names a missing value
    text = re.sub(
        r"<!-- table:(\w+) -->.*?<!-- /table -->",
        lambda m: "<!-- table:" + m.group(1) + " -->\n" + T.TABLES[m.group(1)]() + "\n<!-- /table -->",
        text, flags=re.S,
    )
    Path(out).write_text(text, encoding="utf-8")
    return len(vals)


if __name__ == "__main__":
    template = sys.argv[1] if len(sys.argv) > 1 else "docs/paper_template.md"
    out = sys.argv[2] if len(sys.argv) > 2 else "paper.md"
    print(f"wrote {out} from {template} ({build(template, out)} values)")
